name: "Psalm PHP checks"

on:
    pull_request:
        paths:
            - "composer.json"
            - "**.php"
            - "psalm.xml"
            - ".github/workflows/psalm.yaml"
    push:
        paths:
            - "composer.json"
            - "**.php"
            - "psalm.xml"
            - ".github/workflows/psalm.yaml"

jobs:
    psalm:
        name: Psalm
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master

            -   name: Psalm
                uses: docker://vimeo/psalm-github-actions
                with:
                    args: --shepherd
                    composer_require_dev: true
                    composer_ignore_platform_reqs: true
